#Linux
FROM quay.io/projectquay/golang:1.20 as linuxbuilder

WORKDIR /go/src/app
COPY . .
ARG TARGETARCH
RUN make linux TARGETARCH=$TARGETARCH

FROM scratch as linuxbase
WORKDIR /
COPY --from=linuxbuilder /go/src/app/kbot .
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["./telegram_bot", "start"]
